### ISSUE TITLE
Tapping chain server tray item should go to the Mobile Wallet

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrandroid#17]
When Decred Chain Server is running in the tray, tapping on it should take the user to the Decred Mobile Wallet app. Currently nothing happens.

**Comment by C-ollins** [comment]
This has been solved [here](https://github.com/raedahgroup/dcrandroid/commit/4a3e933a3d408fe34a29468ecc1e5c7afdec2a80)
