### ISSUE TITLE
Rescan button does not work

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrandroid#20]
When I try to do a rescan, the rescan completes instantly without doing anything. Seems to be because I already ran it once this session.

edit, actually rescan is not working at all on the latest version.

**Comment by C-ollins** [comment]
The rescan starts from the last block height it stopped.
The rescan in the settings starts from 0.

**Comment by raedah** [comment]
fixed in https://github.com/raedahgroup/dcrandroid/commit/0f58875945e6663429a9f06854de38017caf3fb3
